# Generated by Django 4.2.29 on 2026-03-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('ldap', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('extension_number', models.CharField(max_length=20)),
                ('server_name', models.CharField(max_length=100)),
                ('number_of_servers', models.PositiveIntegerField()),
                ('rack_space_units', models.PositiveIntegerField()),
                ('power_per_server', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cpu_gpu_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
