# Generated by Django 4.2.29 on 2026-04-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrequest',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
